function data() {
  return {
    Ingredients: [
      {
        Name: 'Garlic',
        Type: 'Spices',
        Variety: 'French Pink',
        Quantity: 6,
        Measure: 'Unit',
      },
      {
        Name: 'Potatoes',
        Type: 'Vegetables',
        Variety: 'Red',
        Quantity: 12,
        Measure: 'Unit',
      },
      {
        Name: 'Salt',
        Type: 'Spices',
        Variety: 'Coarse Salt',
        Quantity: 1,
        Measure: 'Kilogram',
      },
      {
        Name: 'Milk',
        Type: 'Dairy',
        Variety: 'Full Fat',
        Quantity: 2.5,
        Measure: 'Litre',
      },
      {
        Name: 'Bread',
        Type: 'Bread',
        Variety: 'Rye',
        Quantity: 3,
        Measure: 'Unit',
      },
      {
        Name: 'Cookies',
        Type: 'Snacks',
        Variety: 'Chocolate Chip',
        Quantity: 10,
        Measure: 'Unit',
      },
      {
        Name: 'Apple',
        Type: 'Fruit',
        Variety: 'Royal Gala',
        Quantity: 5,
        Measure: 'Unit',
      },
      {
        Name: 'Apple',
        Type: 'Fruit',
        Variety: 'Golden Delicious',
        Quantity: 2,
        Measure: 'Unit',
      },
      {
        Name: 'Orange',
        Type: 'Fruit',
        Variety: 'Valencia',
        Quantity: 4,
        Measure: 'Unit',
      },
      {
        Name: 'Cheese',
        Type: 'Dairy',
        Variety: 'Mozzarella',
        Quantity: 0.5,
        Measure: 'Kilogram',
      },
      {
        Name: 'Cheese',
        Type: 'Dairy',
        Variety: 'Gorgonzola',
        Quantity: 0.35,
        Measure: 'Kilogram',
      },
      {
        Name: 'Cheese',
        Type: 'Dairy',
        Variety: 'Emmental',
        Quantity: 0.7,
        Measure: 'Kilogram',
      },
      {
        Name: 'Chicken Breasts',
        Type: 'Meat',
        Variety: 'Poultry Meat',
        Quantity: 1.2,
        Measure: 'Kilogram',
      },
      {
        Name: 'Turkey Legs',
        Type: 'Meat',
        Variety: 'Poultry Meat',
        Quantity: 0.9,
        Measure: 'Kilogram',
      },
      {
        Name: 'Seabass',
        Type: 'Fish',
        Variety: 'Frozen Fish',
        Quantity: 0.75,
        Measure: 'Kilogram',
      },
      {
        Name: 'Cake',
        Type: 'Snacks',
        Variety: 'Chocolate & Walnut',
        Quantity: 0.6,
        Measure: 'Kilogram',
      },
      {
        Name: 'Yogurt',
        Type: 'Dairy',
        Variety: 'Strawberry',
        Quantity: 3,
        Measure: 'Unit',
      },
      {
        Name: 'Muffin',
        Type: 'Snacks',
        Variety: 'Blueberry',
        Quantity: 2,
        Measure: 'Unit',
      },
      {
        Name: 'Sliced Bread',
        Type: 'Bread',
        Variety: 'Wheat',
        Quantity: 6,
        Measure: 'Unit',
      },
      {
        Name: 'Rice',
        Type: 'Garnish',
        Variety: 'Thai',
        Quantity: 2,
        Measure: 'Kilogram',
      },
      {
        Name: 'Pasta',
        Type: 'Garnish',
        Variety: 'Spaghetti',
        Quantity: 1.75,
        Measure: 'Kilogram',
      },
      {
        Name: 'Cucumber',
        Type: 'Vegetables',
        Variety: '-',
        Quantity: 1,
        Measure: 'Unit',
      },
      {
        Name: 'Zuchini',
        Type: 'Vegetables',
        Variety: '-',
        Quantity: 2,
        Measure: 'Unit',
      },
      {
        Name: 'Carrot',
        Type: 'Vegetables',
        Variety: '-',
        Quantity: 10,
        Measure: 'Unit',
      },
      {
        Name: 'Lettuce',
        Type: 'Vegetables',
        Variety: 'Romaine',
        Quantity: 2.2,
        Measure: 'Kilogram',
      },
      {
        Name: 'Oregano',
        Type: 'Spices',
        Variety: '-',
        Quantity: 0.15,
        Measure: 'Kilogram',
      },
      {
        Name: 'Paprika',
        Type: 'Spices',
        Variety: '-',
        Quantity: 0.25,
        Measure: 'Kilogram',
      },
      {
        Name: 'Wine',
        Type: 'Alcohol',
        Variety: 'Port Wine',
        Quantity: 0.5,
        Measure: 'Litre',
      },
      {
        Name: 'Champagne',
        Type: 'Alcohol',
        Variety: 'Moët & Chandon',
        Quantity: 1.1,
        Measure: 'Litre',
      },
      {
        Name: 'Mushrooms',
        Type: 'Vegetables',
        Variety: 'Brown',
        Quantity: 0.85,
        Measure: 'Kilogram',
      },
      {
        Name: 'Tomatoes',
        Type: 'Vegetables',
        Variety: 'Bradley',
        Quantity: 4,
        Measure: 'Unit',
      },
      {
        Name: 'Tomatoes',
        Type: 'Vegetables',
        Variety: 'Red Cherry',
        Quantity: 12,
        Measure: 'Unit',
      },
      {
        Name: 'Onions',
        Type: 'Vegetables',
        Variety: 'White',
        Quantity: 3,
        Measure: 'Unit',
      },
    ],
    Recipes: [
      {
        Name: 'Mac and Cheese',
        Ingredients: ['Mac', 'Cheese'],
        Recipe: 'Put the Mac in the Cheese and ta da',
        Calories: 500,
        Tags: ['Vegetarian', 'Lactose', 'Pasta'],
        Meal: 'Lunch or Dinner',
        Serving: 1,
        Duration: 8,
        Difficulty: 'Easy',
        Image:
          'https://pinchofyum.com/wp-content/uploads/2014/02/healthy-mac-and-cheese-51.jpg',
      },
      {
        Name: 'Meatballs and Rice',
        Ingredients: ['Meatballs', 'Rice'],
        Recipe: 'Do something with the meatballs and rice',
        Calories: 700,
        Tags: ['Meat'],
        Meal: 'Lunch or Dinner',
        Serving: 4,
        Duration: 65,
        Difficulty: 'Medium',
        Image:
          'https://144f2a3a2f948f23fc61-ca525f0a2beaec3e91ca498facd51f15.ssl.cf3.rackcdn.com/uploads/food_portal_data/recipes/recipe/hero_article_image/2335/letterbox_Saucy-meatballs-with-rice-593.jpg',
      },
      {
        Name: 'Pancakes',
        Ingredients: ['Flour', 'Butter', 'Eggs', 'Milk'],
        Recipe: 'Put it all together and hope for the best',
        Calories: 200,
        Tags: ['Vegetarian'],
        Meal: 'Breakfast or Brunch',
        Serving: 2,
        Duration: 15,
        Difficulty: 'Medium',
        Image:
          'https://images-gmi-pmc.edge-generalmills.com/df109202-f5dd-45a1-99b4-f10939afd509.jpg',
      },
    ],
  };
}

export default data;
